name: TestySite
favicon: null
layout_spectrum: 0.7020790472161025
typography_spectrum: 0.16834491561166942
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.18050298490561545
  lightness: 0.25429550907574594
  saturation: 0.6498304510023445
  rhythmicContrast: 0.342308217426762
purpose: []
